#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE

#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status $app >/dev/null
then
	ynh_script_progression "Removing $app service integration..."
	yunohost service remove $app
fi

ynh_config_remove_systemd

ynh_config_remove_nginx

# Remove logs
#REMOVEME? (Apps should not remove their log dir during remove ... this should only happen if --purge is used, and be handled by the core...) ynh_safe_rm "/var/log/$app"

# Remove local db, search indexes and working files
ynh_safe_rm "/var/lib/opencast"

# Remove configuration files
ynh_safe_rm "/etc/opencast"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
